### ISSUE TITLE
Make suggestionAction: SuggestionAction.unfocus as default

### ISSUE THREAD

**Issue by bebaoboy** [maheshj01/searchfield#151]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Make `onOutSideTap` close the suggestion box by default. Right now, user has to use `focusNode` to close the suggestion box manually. If the user doesn't know or is new to the package, it can put them in an uneasy situation to find a way to do that.
Or we can update the document to show the user how to close the panel in a clear and straightforward section, with clear section name. 

![image](https://github.com/user-attachments/assets/a39b2d66-9fca-4598-85f8-884725a87bf3)

**Describe alternatives you've considered**

**Comment by maheshmnj** [comment]
I completely agree, I had that on my mind before, I think the challenge here is identifying the global TapOutSide, Searchfield has its own TapOutSide which is built by combining taps on TextField + Suggestions I believe to understand whether Searchfield has Focus,  I can't think of it at this time.

**Comment by maheshj01** [comment]
By just passing `suggestionAction: SuggestionAction.unfocus,` will close the suggestion box  We should make this behavior as default

**Comment by maheshj01** [comment]
Published in [v1.2.0](https://pub.dev/packages/searchfield/changelog)
