### ISSUE TITLE
[Proposal] Add height parameter for suggestion dialog

### ISSUE THREAD

**Issue by elijahpraise** [maheshj01/searchfield#164]
When the suggestions are past the max suggestions in viewport, the dialog is scrollable, while this is fine, I humbly request that you add a nullable height parameter that will default to the total height if not specified.

**Comment by elijahpraise** [comment]
Just seeing this parameter now. Thanks so much. I saw it on the latest
release

**Comment by maheshj01** [comment]
Closing as the feature already exist, Incase you encounter a bug or have a feature request feel free to file a new issue.

Best,
Mahesh

**Comment by elijahpraise** [comment]
Thanks, I will.
