### ISSUE TITLE
prefixIcon and suffixIcon are missing in SearchInputDecoration in the release of 1.1.0

### ISSUE THREAD

**Issue by twfungi** [maheshj01/searchfield#171]
**Describe the bug**
prefixIcon and suffixIcon are missing in SearchInputDecoration in the release of 1.1.0

**To Reproduce**
Update from 1.0.9 to 1.1.0

**Comment by maheshj01** [comment]
Hi @twfungi Thanks for filing the issue, These properties were added https://github.com/maheshj01/searchfield/commit/dc5877c01809bb99c6c46691f9e31a0a9d0f1361 and should be available in next release.

**Comment by szastavnyy** [comment]
please add also "suffix", not only "suffixIcon". thx in advance

**Comment by maheshj01** [comment]
released in [v1.1.1](https://pub.dev/packages/searchfield/changelog)
