### ISSUE TITLE
SearchInputDecoration should overwrite copyWith

### ISSUE THREAD

**Issue by franzlst** [maheshj01/searchfield#175]
**Describe the bug**

The newly introduced class `SearchInputDecoration` subclasses `InputDecoration`, but does not overwrite the method `copyWith`. Therefore, it is not possibly to call `copyWith` on a `SearchInputDecoration` object and assign it to the `searchInputDecoration` parameter, as `copyWith` returns an `InputDecoration`.

**Comment by maheshj01** [comment]
Fixed and released in [searchfield: ^1.1.2](https://pub.dev/packages/searchfield/changelog)

**Comment by maheshj01** [comment]
edit fixed in 1.1.3

**Comment by franzlst** [comment]
Thank you!
