### ISSUE TITLE
SearchInputDecoration class is not taking the affect of any attribute inside it 

### ISSUE THREAD

**Issue by rahaf-malas** [maheshj01/searchfield#176]
When I try to set the SearchInputDecoration value to change the text field style, it doesn't take affect, and the default style keeps remain, although I have InputDecorationTheme in myApp widget. when try older versions of the package (0.X.X) versions it works well. Any thoughts?

this is my code snippet for the input styling part:

```dart
searchInputDecoration: SearchInputDecoration(
        filled: true,
        contentPadding: const EdgeInsets.all(10),
        fillColor: KeyperColors.lightGrey,
        hintText: 'Search area or building',
        hintStyle: const TextStyle(
            color: KeyperColors.lightDetails,
            fontSize: 15,
            fontWeight: FontWeight.w400),
        prefixIcon: Padding(
          padding: const EdgeInsets.all(10),
          child: Image.asset(
            ImageConstants.searchIcon,
            height: 16,
            color: KeyperColors.lightDetails,
          ),
        ),
        enabledBorder: OutlineInputBorder(
            borderSide: const BorderSide(
                width: 1, color: KeyperColors.lightGrey),
            borderRadius: BorderRadius.circular(43)),
        focusedBorder: OutlineInputBorder(
            borderSide: const BorderSide(
                width: 1, color: KeyperColors.lightGrey),
            borderRadius: BorderRadius.circular(43)),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(43.0),
        ),
      ),
                                  
```
********** flutter --version
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (4 months ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

**Comment by maheshj01** [comment]
Hi @rahaf-malas, Thanks for filing the issue. I really appreciate pointing that out quick. 

related to #175 

The issue has been fixed and released in [v1.1.3 ](https://pub.dev/packages/searchfield/changelog)

Closing as fixed
