### ISSUE TITLE
enable/disable

### ISSUE THREAD

**Issue by szastavnyy** [maheshj01/searchfield#181]
please add enable property.
the same as 
https://api.flutter.dev/flutter/material/InputDecoration/enabled.html
thanks in advance

**Comment by maheshj01** [comment]
Hey @szastavnyy enabled property is already present in Searchfield 

`Searchfield.enabled`: Defines whether to enable the searchfield defaults to true

**Comment by maheshj01** [comment]
Closing as invalid.
