### ISSUE TITLE
When closing the keyboard, the search results gets lost

### ISSUE THREAD

**Issue by anas43950** [maheshj01/searchfield#183]
When I search for something using the on-screen keyboard in mobile, and then close the keyboard, the search results are lost.
I've attached a video demonstrating the same.

https://github.com/user-attachments/assets/2ba109a5-7395-4e85-a028-18632f967fe8

**Comment by anas43950** [comment]
Sorry, the issue was related to ScreenUtil, it was rebuilding the widget unnecessarily, it's working fine now, sorry about that

**Comment by maheshj01** [comment]
No worries, glad you found the issue.

**Comment by sabari7320** [comment]
same issue i also can you tell me how did you find  @anas43950 ?
my code is  SearchField(
                                autovalidateMode: AutovalidateMode.onUserInteraction,
                                onTapOutside: null,
                                // onTap: (){
                                //   if(!stateList.contains(stateController.text)){
                                //     setState(() {
                                //       stateController.clear();
                                //     });
                                //   }
                                // },

                                focusNode: _otherTextFieldFocusNode,
                                suggestionStyle: TextStyle(decoration: TextDecoration.none),
                                searchInputDecoration: SearchInputDecoration(
                                  border: InputBorder.none,
                                  labelText: 'State',
                                  enabledBorder: OutlineInputBorder(
                                      borderSide: BorderSide(color: Colors.grey),
                                      borderRadius: BorderRadius.circular(10)),
                                  focusedBorder: OutlineInputBorder(
                                      borderSide: BorderSide(color: Colors.grey),
                                      borderRadius: BorderRadius.circular(10)),
                                  disabledBorder: OutlineInputBorder(
                                      borderSide: BorderSide(color: Colors.grey),
                                      borderRadius: BorderRadius.circular(10)),
                                  errorBorder: OutlineInputBorder(
                                      borderSide: BorderSide(color: Colors.red),
                                      borderRadius: BorderRadius.circular(10)),
                                  focusedErrorBorder:OutlineInputBorder(
                                      borderSide: BorderSide(color: Colors.red),
                                      borderRadius: BorderRadius.circular(10)),
                                  hintStyle: TextStyle(color: Colors.black),
                                  contentPadding: const EdgeInsets.symmetric(vertical: 1.0, horizontal: 15),
                                ),

                                onSuggestionTap: (selectedValue) {
                                  print("Selected state: ${selectedValue.item}");
                                  stateController.text = selectedValue.item!;
                                  fetchCityList(countryController.text, selectedValue.item!);
                                  FocusScope.of(context).unfocus();
                                },
                                suggestions: stateList.isEmpty
                                ? [SearchFieldListItem("No state available", child: Text("No state available"))]
                                    :stateList.map((state) => SearchFieldListItem(
                                  state,
                                  item: state,
                                  child: Padding(
                                    padding: const EdgeInsets.all(8.0),
                                    child: Text(state),
                                  ),
                                ))
                                    .toList(),
                                itemHeight: 55,
                                maxSuggestionsInViewPort: 4,
                                controller: stateController,
                                validator: (selectedValue) {
                                  if (selectedValue == null || !stateList.contains(selectedValue)) {
                                    return 'Please select State';
                                  }
                                  return null;
                                },
                              ),

**Comment by anas43950** [comment]
@sabari7320 My issue was related to screenUtil package, I had set rebuild widget to everytime (I don't remember the exact property name and value), it was in the ScreenUtilInit widget wrapping the material app in the main.dart file

**Comment by sabari7320** [comment]
ok Let me check and Thankyou for you quick response
