### ISSUE TITLE
customize localization to arabic to make suggestion start from right 

### ISSUE THREAD

**Issue by abdelrahman1820** [maheshj01/searchfield#184]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maheshj01** [comment]
Hi @abdelrahman1820, You can pass in the custom widget using the child parameter 

```dart
SearchField(
  suggestions: _statesOfIndia
     .map((e) => SearchFieldListItem(e,
        child: Align(
          alignment: Alignment.centerRight,
          child: Padding(
             padding: const EdgeInsets.symmetric(horizontal:16.0),
               child: Text(e,
                 style: TextStyle(color: Colors.red),
               ),
             ),
          ))).toList(),
    ...
    ...
)
```

**Comment by maheshj01** [comment]
@abdelrahman1820 I am going to close this issue as stale, If there any more queries or if you need help with the package please file a new issue.
