### ISSUE TITLE
Please add contextMenuBuilder field

### ISSUE THREAD

**Issue by szastavnyy** [maheshj01/searchfield#188]
Hello. Thanks again for nice library. 
Please add field "contextMenuBuilder" and pass it to TextFormField inside, so we can create custom text selection menu.
Thanks in advance!

**Comment by maheshj01** [comment]
ref: https://api.flutter.dev/flutter/material/TextField/contextMenuBuilder.html

**Comment by maheshj01** [comment]
Published in latest release.

cc: @szastavnyy

**Comment by szastavnyy** [comment]
have checked. works fine. thanks again !
