### ISSUE TITLE
[Breaking] Proposal to handle selectedValue on the client side

### ISSUE THREAD

**Issue by maheshj01** [maheshj01/searchfield#191]
This issue proposes a change in how the value is selected in the SearchField component. Several bugs have been reported, such as breakdowns in keyboard navigation and selection highlighting. These issues can be resolved by explicitly managing the selectedValue in the consumer code.

Currently, the package automatically sets the selectedValue in the input field, which causes inconsistencies, especially when dealing with keyboard navigation and item highlighting.

**Before**
The package sets the selectedValue automatically inside the component, which leads to issues when navigating or selecting suggestions

```dart
SearchField(
    hint: 'Basic SearchField',
    dynamicHeight: true,
    maxSuggestionBoxHeight: 300,
    initialValue: SearchFieldListItem<String>('ABC'),
    suggestions: dynamicHeightSuggestion
        .map(SearchFieldListItem<String>.new)
        .toList(),
    suggestionState: Suggestion.expand,
),
```

**After**

We suggest that the selectedValue be managed explicitly in the client code (consumer code) by using the `onSuggestionTap` callback. This approach simplifies the API and provides more accurate control over the internal state of the package.

```dart
var selectedValue = SearchFieldListItem<String>('ABC');

SearchField(
    hint: 'Basic SearchField',
    dynamicHeight: true,
    maxSuggestionBoxHeight: 300,
    onSuggestionTap: (SearchFieldListItem<String> item) {
        setState(() {
        selectedValue = item;
        });
    },
    selectedValue: selectedValue,
    suggestions: dynamicHeightSuggestion
        .map(SearchFieldListItem<String>.new)
        .toList(),
    suggestionState: Suggestion.expand,
),
```

This change will make it clearer and more predictable how the selected value is handled and displayed, and it will improve keyboard navigation and item highlighting.

**Comment by maheshj01** [comment]
@sabari7320 Before I merge this would you want to try this out on your end and see if this also fixes your issue?

```yaml
 searchfield:
    git:
      url: https://github.com/maheshmnj/searchfield.git
      ref: breaking-design
```

**Comment by sabari7320** [comment]
The issue is still present. Steps to reproduce the error:

1)Search for something.
2.)Related values appear.
3.)Click the close button.
4.)The full list of values appears again from the beginning.

**Comment by maheshj01** [comment]
@sabari7320  lets continue the discussion here https://github.com/maheshj01/searchfield/issues/190

**Comment by maheshj01** [comment]
[v1.2.0](https://pub.dev/packages/searchfield/changelog) is now live on pub.dev see the Changelog for details.
