### ISSUE TITLE
Flutter Flutter 3.27.0 compatibility

### ISSUE THREAD

**Issue by gruuna** [maheshj01/searchfield#195]
**The bug**

With the newly released version of Flutter I get the following error trying to compile our app:

`searchfield-1.2.0/lib/src/input_decoration.dart:128:25: Error: The method 'SearchInputDecoration.copyWith' doesn't have the named parameter 'maintainHintHeight' of overridden method 'InputDecoration.copyWith'.
  SearchInputDecoration copyWith({
                        ^
../../../flutter/packages/flutter/lib/src/material/input_decorator.dart:3597:19: Context: This is the overridden method ('copyWith').
  InputDecoration copyWith({
                  ^`

Seems like the copyWith method does not fit to InputDecoration of Flutter material anymore...

**Comment by maheshj01** [comment]
Hi @gruuna, Thanks for filing the issue. Will take a look at it asap.

**Comment by maheshj01** [comment]
@gruuna Published a new release v1.2.1 Thank you for bring this up quick. Issues like these help searchfield keep up with flutter releases.
