### ISSUE TITLE
[Proposal] Dynamic Item height

### ISSUE THREAD

**Issue by haaris94** [maheshj01/searchfield#67]
**Is your feature request related to a problem? Please describe.**
See this example: [Image link](https://imgur.com/a/KDStoR4) 
As you can see, the string is divided using `\n` to form multiple lines. The string can have no breaks or up to 5-7 breaks. Right now I am putting empty dashes in new line to fill up the space.

**Describe the solution you'd like**
Can we have dynamic `itemHeight` Like if I did not specify the height, it should be dynamic

**Comment by maheshmnj** [comment]
Hi @haaris94, thats a great feature request though. But I cannot promise a timeline due to other commitments.
Anyone who is interested feel free to send a PR and I can definitely review it.

**Comment by bebaoboy** [comment]
I'm on it, will add a PR soon 🤗

**Comment by maheshj01** [comment]
Released in [v1.0.7](https://pub.dev/packages/searchfield/changelog)

Thank you @bebaoboy!
